apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-cart-service-load-test-deployment
  namespace: rss-cart
  labels:
    app: rss-cart
    label: loading
spec:
  replicas: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: rss-cart
      track: load-test
  template:
    metadata:
      labels:
        app: rss-cart
        track: load-test
    spec:
      volumes:
        - name: config
          configMap:
            name: fluent-conf
      containers:
      - name: fluentd
        ports: 
        - containerPort: 24224
        image: grafana/fluent-plugin-loki:latest
        env:
        - name: LOKI_URL
          value: http://loki:3100
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf

      - name: rss-cart
        image: 855430746673.dkr.ecr.us-east-1.amazonaws.com/matt-oberlies-sre-p3-rss-cart:latest
        ports:
        - containerPort: 9999
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9999
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 9999
          initialDelaySeconds: 15
          periodSeconds: 3
          failureThreshold: 5
        env:
        - name: DB_URL
          valueFrom: 
            secretKeyRef:
              name: rss-cart-credentials
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rss-cart-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rss-cart-credentials
              key: password
      
