{
 "title": "Cart Microservice",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pod Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_created{namespace=\"rss-cart\"})",
     "legendFormat": "podname: {{pod}}"
    }
   ]
  },
  {
   "title": "Pods Availability",
   "type": "stat",
   "description": "Number of active pods",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count:up1{job=\"rss-cart-service\"}"
    }
   ]
  },
  {
   "title": "Downtime Percentage For Current Time Interval",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((((sum(up{job=\"rss-cart-service\"})) OR on() vector(0)) == 0) + 1) OR on() vector(0))",
     "legendFormat": "Using job"
    },
    {}
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "gauge",
   "description": "Current average CPU Usage of 3 pods for job=rss-cart-service ",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_cpu_usage{job=\"rss-cart-service\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"rss-cart-service\"}*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"rss-cart\", container=\"rss-cart\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Successful Requests Rate",
   "type": "gauge",
   "description": "for job = rss-cart-service",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"rss-cart-service\", url!~\"/actuator/.*\", status!~\"5..\"})\n/\nsum(http_server_requests_seconds_count{job=\"rss-cart-service\", url!~\"/actuator/.*\"})\n* 100"
    }
   ]
  },
  {
   "title": "30 days SLO ",
   "type": "graph",
   "description": "for rss-cart-service",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "99.5", "legendFormat": "target" },
    {
     "expr": "( ( sum by(job) (rate(http_server_requests_seconds_sum{job=\"rss-cart-service\", uri!=\"/actuator.*\", status!~\"5..\"}[1d])) \n/ \nsum by (job) (rate(http_server_requests_seconds_count{job=\"rss-cart-service\", uri!=\"/actuator.*\", status!~\"5..\"}[1d])) ) < 1.2)\n/\n( ( sum by(job) (rate(http_server_requests_seconds_sum{job=\"rss-cart-service\", uri!=\"/actuator.*\"}[1d])) \n/ \nsum by (job) (rate(http_server_requests_seconds_count{job=\"rss-cart-service\", uri!=\"/actuator.*\"}[1d])) ) >= 0 )\n*100",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Error Burn Rate 1",
   "type": "graph",
   "description": "Severity: Warning",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RSScart_http_request_error_rate:burnrate3d",
     "legendFormat": "3d"
    },
    {
     "expr": "RSScart_http_request_error_rate:burnrate6h",
     "legendFormat": "6h"
    },
    { "expr": "1 * (1-0.995000)", "legendFormat": "Alert Threshold" }
   ]
  },
  {
   "title": "Error Burn Rate 3",
   "type": "graph",
   "description": "Severity: Warning",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RSScart_http_request_error_rate:burnrate1d",
     "legendFormat": "1d"
    },
    {
     "expr": "RSScart_http_request_error_rate:burnrate2h",
     "legendFormat": "2h"
    },
    { "expr": "3 * (1-0.995000)", "legendFormat": "Alert Threshold" }
   ]
  },
  {
   "title": "Error Burn Rate 6",
   "type": "graph",
   "description": "Severity: Critical",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RSScart_http_request_error_rate:burnrate30m",
     "legendFormat": "30m"
    },
    {
     "expr": "RSScart_http_request_error_rate:burnrate6h",
     "legendFormat": "6h"
    },
    { "expr": "6 * (1-0.995000)", "legendFormat": "Alert Threshold" }
   ]
  },
  {
   "title": "Error Burn Rate 14.4",
   "type": "graph",
   "description": "Severity: Critical",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RSScart_http_request_error_rate:burnrate1h",
     "legendFormat": "1h"
    },
    {
     "expr": "RSScart_http_request_error_rate:burnrate5m",
     "legendFormat": "5m"
    },
    { "expr": "14.4 * (1-0.995000)", "legendFormat": "Alert Threshold" }
   ]
  },
  {
   "title": "High Latency Burn Rate ",
   "type": "graph",
   "description": "Severity: Warning",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RSScart_http_request_latency:burnrate1d",
     "legendFormat": "1d"
    },
    {
     "expr": "RSScart_http_request_latency:burnrate2h",
     "legendFormat": "2h"
    },
    {
     "expr": "RSScart_http_request_latency:burnrate3d",
     "legendFormat": "3d"
    },
    {
     "expr": "RSScart_http_request_latency:burnrate6h",
     "legendFormat": "6h"
    },
    { "expr": "3 * (1-0.995000)", "legendFormat": "Burn rate 3" },
    { "expr": "1 * (1-0.995000)", "legendFormat": "Burn rate 1" }
   ]
  },
  {
   "title": "High Latency Burn Rate",
   "type": "graph",
   "description": "Severity: Critical",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "RSScart_http_request_latency:burnrate1h",
     "legendFormat": "1h"
    },
    {
     "expr": "RSScart_http_request_latency:burnrate5m",
     "legendFormat": "5m"
    },
    {
     "expr": "RSScart_http_request_latency:burnrate6h",
     "legendFormat": "6h"
    },
    {
     "expr": "RSScart_http_request_latency:burnrate30m",
     "legendFormat": "30m"
    },
    { "expr": "14.4 * (1-0.995000)", "legendFormat": "Burn rate 14.4" },
    { "expr": "6 * (1-0.995000)", "legendFormat": "Burn rate 6" }
   ]
  },
  {
   "title": "Average HTTP Requests per Second",
   "type": "graph",
   "description": "for Cart Service [1 min] to monitor load balancing between 3 pods",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"rss-cart-service\"}[1m])) by (instance,pod)",
     "legendFormat": "{{instance}}, {{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"rss-cart-service\"}[1m])) by (method, uri) \n/ \nsum(rate(http_server_requests_seconds_count{job=\"rss-cart-service\"}[1m])) by (method, uri)",
     "legendFormat": "{{method}}, {{uri}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{service=\"rss-cart-service\"}"
    }
   ]
  },
  {
   "title": "Rate of Logback Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{namespace=\"rss-cart\"}[1h])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}