apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rss-cart-prometheus-rules
  namespace: rss-cart
  labels:
    app: rss-cart
    job: rss-cart-service
    release: kube-prometheus-stack
    app: kube-prometheus-stack
    team: sre
spec:
  groups: 
  - name: rsscartSLOs-http_requests_total
    rules:
    - alert: RSSCart:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-cart-service (current value: {{ $value }})'
      expr: |
        sum(RSSCart:http_request_error_count:burnrate5m{job="rss-cart-service"}) > (14.40 * (1-0.99500))
        and
        sum(RSSCart:http_request_error_count:burnrate1h{job="rss-cart-service"}) > (14.40 * (1-0.99500))
      for: 2m
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
        severity: page
    - alert: RSSCart:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-cart-service (current value: {{ $value }})'
      expr: |
        sum(RSSCart:http_request_error_count:burnrate30m{job="rss-cart-service"}) > (6.00 * (1-0.99500))
        and
        sum(RSSCart:http_request_error_count:burnrate6h{job="rss-cart-service"}) > (6.00 * (1-0.99500))
      for: 15m
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
        severity: page
    - alert: RSSCart:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-cart-service (current value: {{ $value }})'
      expr: |
        sum(RSSCart:http_request_error_count:burnrate2h{job="rss-cart-service"}) > (3.00 * (1-0.99500))
        and
        sum(RSSCart:http_request_error_count:burnrate1d{job="rss-cart-service"}) > (3.00 * (1-0.99500))
      for: 1h
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
        severity: ticket
    - alert: RSSCart:ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=rss-cart-service (current value: {{ $value }})'
      expr: |
        sum(RSSCart:http_request_error_count:burnrate6h{job="rss-cart-service"}) > (1.00 * (1-0.99500))
        and
        sum(RSSCart:http_request_error_count:burnrate3d{job="rss-cart-service"}) > (1.00 * (1-0.99500))
      for: 3h
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
        severity: ticket
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[1d]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service"}[1d]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate1d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[1h]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service"}[1h]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate1h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[2h]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service"}[2h]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate2h
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[30m]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service"}[30m]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate30m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[3d]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service"}[3d]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate3d
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[5m]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service"}[5m]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate5m
    - expr: |
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*", status=~"5.."}[6h]))
        /
        sum(rate(http_server_requests_seconds_count{job="rss-cart-service", url!~"/actuator/.*"}[6h]))
      labels:
        app: rss-cart
        job: rss-cart-service
        release: kube-prometheus-stack
      record: RSSCart:http_request_error_count:burnrate6h