apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test
  namespace: rss-cart
  labels:
    #app: rss-cart
    job: rss-cart-service
    release: kube-prometheus-stack
    app: kube-prometheus-stack
    team: sre
spec:
  groups:
  - name: rsscartTest
    rules:
    - alert: RSSCartTest
      annotations:
        summary: '[TestAlert] [{{ $labels.severity }}] High requests latency budget burn for {{ $labels.app }}'
        description: 'High latency ({{ $labels.latency}}s) ratio exceeds burn rate for job {{ $labels.job }}. Current value is {{ $value }} for {{ $labels.window }} window.'        
        message: '[Test] High requests latency budget burn for job=rss-cart-service,latency=1.2 (current value: {{ $value }})'
      expr: |
        rsscarttest:http_request_latency:burnrate1d{job="rss-cart-service"} > (3*(1-0.995000))
      labels:
        job: rss
        
    #record
    - record: rsscarttest:http_request_latency:burnrate1d
      expr: |
        ( 1 - 
        ( sum by(job) (rate(http_server_requests_seconds_sum{job="rss-cart-service"}[1d])) 
          / 
          sum by (job) (rate(http_server_requests_seconds_count{job="rss-cart-service"}[1d])) < 1.2 )
        )
        /
        ( sum by(job) (rate(http_server_requests_seconds_sum{job="rss-cart-service"}[1d])) 
        / 
        sum by (job) (rate(http_server_requests_seconds_count{job="rss-cart-service"}[1d])) >= 0.0
        )
      labels:
        app: rss-cart
        job: rss-cart-service
        latency: "1.2"
        window: "1 day"
        severity: CRITICAL